config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  get 'welcome/index'
  root "welcome#index"

  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  has_attached_file :image, styles: { large: "600x600>", medium: "500x500>", thumb: "100x100#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  geocoded_by :address
   after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   geocoded_by :address
   after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if params[:search].present?
        @books = Book.near(params[:search], 3, units: :km)
    else
        @books = Book.all
    end
  end 

  def show
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to root_path }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to root_path }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :description, :image, :price).merge(user_id: current_user.id, address: current_user.address)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	def edit
	end

	def update
	    @user = User.find(current_user.id)
	    respond_to do |format|
	      if @user.update(user_params)
	        format.html { redirect_to root_url }
	        format.json { render :show, status: :ok, location: @user }
	      else
	        format.html { render :edit }
	        format.json { render json: @user.errors, status: :unprocessable_entity }
	      end
	    end
	end

  	protected
	  def update_resource(resource, params)
	    resource.update_without_password(params)
	  end

  	private
	    def sign_up_params
	      params.require(:user).permit(:email, :password, :password_confirmation, :address)
	    end

	    # Never trust parameters from the scary internet, only allow the white list through.
	    def user_params
	      params.require(:user).permit(:email, :password, :password_confirmation, :address)
	    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	 @books = Book.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="form-group  ">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group  ">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group  ">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  
  <div class="actions">
    <%= f.submit class: "green-btn" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h2>edit book</h2>
<%= render 'form', book: @book %>

app/views/books/index.html.erb
<div style="margin-top: 40px;">
	<% if params[:search].present? %>
        <h2 style="color: #3C472F">Books near <span style="color: #223d61"><%= params[:search] %></span></h2>
    <% end %>
	<% @books.each do |book| %>
		<div class="book">
			<div class="row">
				<%= link_to book do %>
				<div class="col-md-2">
					<%= image_tag book.image.url(:large), class: "book-img" %>
				</div>
				<div class="col-md-2">
					<h2 class="book-title" style="color: #333333"><%= book.title %></h2>
				</div>
				<div class="col-md-8">
						<%= image_tag "281767.svg", id: "google_map" %>
						<h3 class="book-price"><%= number_to_currency(book.price, unit: "") %> $</h3>
						(<%= book.distance.round(2) %>, miles)
				</div>
				<% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/books/new.html.erb
<h2>new book</h2>
<%= render 'form', book: @book %>

app/views/books/show.html.erb
<div style="margin-top: 40px;">
	<div class="row">
		<div class="col-md-3"><%= image_tag @book.image.url(:large), class: "book-img1" %></div>
		<div class="col-md-3">
			<h2 class="book-title" style="color: #333333"><%= @book.title %></h2>
			<h2 class="book-price"><%= number_to_currency(@book.price, unit: "") %> $</h2>
			<p class="book-description" style="color: #333333"><%= @book.description %></p>

		</div>
	</div>
	
	
	<div id="map"></div>
    <script>
      function initMap() {
        var uluru = {lat: <%= @book.user.latitude %>, lng: <%= @book.user.longitude %> };
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 13,
          center: uluru
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCXYYNHt5bguptWTF27gBIdRe4Vmz05rUw&callback=initMap">
    </script>

    <h1>Nearby books</h1>
	    <% for book in @book.nearbys(10).first(2) %>
	    	<div class="book">
				<div class="row">
					<%= link_to book do %>
					<div class="col-md-2">
						<%= image_tag book.image.url(:large), class: "book-img" %>
					</div>
					<div class="col-md-2">
						<h2 class="book-title" style="color: #333333"><%= book.title %></h2>
					</div>
					<div class="col-md-8">
							<%= image_tag "281767.svg", id: "google_map" %>
							<h3 class="book-price"><%= number_to_currency(book.price, unit: "") %> $</h3>
							(<%= book.distance.round(2) %>, miles)
					</div>
					<% end %>
				</div>
			</div>
	    <% end %>
</div>

app/views/layouts/_header.html.erb
<% unless current_page?(root_path) %>
<header id="main_menu" class="header navbar-fixed">            
    <div class="main_menu_bg">
        <div class="container">
            <div class="row">
                <div class="nave_menu">
                    <nav class="navbar navbar-default" id="navmenu">
                        <div class="container-fluid">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <%= link_to root_path, class: "navbar-brand" do %>
                                    <p class="logo">near book</p>           
                                <% end %>
                            </div>
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav navbar-right">
                                    <% if current_user %>
                                        <li><%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
                                    <% else %>
                                        <li><%= link_to "Sign up", new_user_registration_path %></li>
                                        <li><%= link_to "Login", new_user_session_path %></li>
                                    <% end %>
                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>  
            </div>
        </div>
    </div>
</header> 
<% else %>
<header id="main_menu" class="header navbar-fixed">            
    <div class="main_menu_bg">
        <div class="container">
            <div class="row">
                <div class="nave_menu">
                    <nav class="navbar navbar-default" id="navmenu">
                        <div class="container-fluid">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                </button>
                                <%= link_to root_path, class: "navbar-brand" do %>
                                    <p class="logo">near book</p> 
                                <% end %>
                            </div>
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav navbar-right">
                                    <% if current_user %>
                                        <li><%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
                                    <% else %>
                                        <li><%= link_to "Sign up", new_user_registration_path %></li>
                                        <li><%= link_to "Login", new_user_session_path %></li>
                                    <% end %>
                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>  
            </div>
        </div>
    </div>
</header> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>near book</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Rubik" rel="stylesheet">
  </head>

  <body>
    <%= render "layouts/header" %>
    	<div class="row">
    		<div class="col-md-7 quds">
    			    <div class="text-center">

				        <h1 style="color: #fff"><%= image_tag "281767.svg", id: "google_map" %>Find books near you</h1>

				        <%= form_tag books_path, :method => :get do %>
				          <p>
				            <%= text_field_tag :search, params[:search], class: "form-control form-width" %>
				            <%= submit_tag "Search", :name => nil, class: "green-btn" %>
				          </p>
				        <% end %>    
				    </div>
    		</div>
    		<div class="col-md-5">
    			<div class="container">
    				<%= yield %>
    			</div>
    		</div>
    	</div>
    
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/welcome/index.html.erb
<div style="margin-top: 80px;">
	<% @books.each do |book| %>
		<div class="book">
		<div class="row">
			<%= link_to book do %>
			<div class="col-md-2">
				<%= image_tag book.image.url(:large), class: "book-img" %>
			</div>
			<div class="col-md-2">
				<h2 class="book-title" style="color: #333333"><%= book.title %></h2>
			</div>
			<div class="col-md-8">
					<%= image_tag "281767.svg", id: "google_map" %>
					<h3 class="book-price"><%= number_to_currency(book.price, unit: "") %> $</h3>
			</div>
			<% end %>
		</div>
		</div>
	<% end %>
</div>